Socint 54 update docker compose for rhsvc
ONSdigital/sdc-int-rh-service pull request #7
Opened 2021-08-05 14:57 UTC by PeterBochel

2021-08-09 08:38 UTC, philwhiles commented on docker/docker-compose-mock-envoy.yml
> +    image: europe-west2-docker.pkg.dev/ons-ci-int/int-docker-snapshot/mock-envoy:update-dependencies
latest surely?

2021-08-09 08:38 UTC, philwhiles commented on docker/docker-compose-rh-service.yml
> +    image: europe-west2-docker.pkg.dev/ons-ci-int/int-docker-snapshot/rh-service:SOCINT-54_Update_docker_compose_for_RHSVC
latest

2021-08-09 08:39 UTC, philwhiles requested changes
latest tweaks I think

2021-08-17 09:23 UTC, rpcatling requested changes

2021-08-17 09:23 UTC, rpcatling commented on README.md
> +There are several ways of running this service
README needs updating to describe additional docker compose mechanisms / scripts and any prereqs.

2021-08-17 09:23 UTC, rpcatling commented on docker/docker-compose-rh-service.yml
> +    image: europe-west2-docker.pkg.dev/ons-ci-int/int-docker-snapshot/rh-service:SOCINT-54_Update_docker_compose_for_RHSVC
Consider using tags so that when we do `docker sp` we get a human readable image name

2021-08-17 09:23 UTC, rpcatling commented on docker/docker-compose-mock-envoy.yml
> +    image: europe-west2-docker.pkg.dev/ons-ci-int/int-docker-snapshot/mock-envoy:update-dependencies
Consider using tags so that when we do `docker sp` we get a human readable image name

2021-08-18 16:00 UTC, PeterBochel commented on docker/docker-compose-rh-service.yml
> +    image: europe-west2-docker.pkg.dev/ons-ci-int/int-docker-snapshot/rh-service:SOCINT-54_Update_docker_compose_for_RHSVC
Now using latest.

2021-08-18 16:00 UTC, PeterBochel commented on docker/docker-compose-mock-envoy.yml
> +    image: europe-west2-docker.pkg.dev/ons-ci-int/int-docker-snapshot/mock-envoy:update-dependencies
Now using latest.

2021-08-18 16:25 UTC, rpcatling commented on README.md
> +* Docker. To run the RH Service and its required mocks you can run a docker compose script. See 'docker/README.md' for details.
be nice if docker/README.md is a link

2021-08-18 16:25 UTC, rpcatling approved these changes

2021-08-19 08:43 UTC, PeterBochel commented on README.md
> +* Docker. To run the RH Service and its required mocks you can run a docker compose script. See 'docker/README.md' for details.
Good idea.  It's now a link

2021-08-23 08:43 UTC, philwhiles approved these changes

2021-08-23 08:43 UTC, merged