Socint 81 swapped rabbit for pubsub
ONSdigital/sdc-int-rh-service pull request #8
Opened 2021-08-18 16:33 UTC by KieranWardle

# Motivation and Context
We're Moving to Google PubSub instead of rabbit

# What has changed
Removed all code & config related to rabbit and replaced with pubsub where applicable
Updated tests to work with pubsub instead

# How to test?
You can use google's pubsub emulator project to test sending and receiving events
https://cloud.google.com/pubsub/docs/emulator

# Links
https://collaborate2.ons.gov.uk/jira/browse/SOCINT-81

2021-08-19 16:15 UTC, rpcatling requested changes
In addition to the specific comments:
- please search for all references to "rabbit" and remove or fix
- note that docker_compose.yml can be removed since it is creating rabbit docker image
- README needs extensive update, in particular to remove rabbit references and replace with pubsub, but also needs detailed description of how to setup your local environment so you can have a working RHSvc.  Suggest explanation of installing and starting the pubsub emulator (with project=local) and then creating all the topics (currently 6 of them defined in EventTopic), and then the subscribers need creating to match the names in application.yml.

2021-08-20 07:39 UTC, rpcatling commented on src/main/resources/application.yml
> +  case-subscription: case-rh-case
if we have a choice I would like to drop the "case-" prefix so that the subscriptions become
- rh-case
- rh-uac

2021-08-20 15:34 UTC, rpcatling approved these changes

2021-08-20 15:37 UTC, rpcatling commented
Approved with the proviso:
- some outstanding references to "rabbit" removed 
- some logging/comments mentioning "responseAuthenticated" should now be "UAC authenticated"
- @PeterBochel  to review README for pub/sub instructions
- @PeterBochel  to discuss possible structure improvements of README , for either now or future

2021-08-24 09:50 UTC, PeterBochel requested changes

2021-08-24 14:28 UTC, PeterBochel approved these changes

2021-08-25 09:48 UTC, merged